import { getPool, execute } from '../lib/db.js';
import bcrypt from 'bcryptjs';
import { v4 as uuidv4 } from 'uuid';

const seedData = async () => {
  try {
    console.log('Connecting to SQL Server...');
    await getPool();

    console.log('Starting database seeding...');

    // Clear existing data (order matters for FK constraints)
    await execute('DELETE FROM Reviews');
    await execute('DELETE FROM Wishlists');
    await execute('DELETE FROM Carts');
    await execute('DELETE FROM Orders');
    await execute('DELETE FROM Products');
    await execute('DELETE FROM Categories');
    await execute('DELETE FROM Users');

    console.log('Cleared existing data');

    // Create categories
    const laptopCategoryId = uuidv4();
    const accessoriesCategoryId = uuidv4();
    const componentsCategoryId = uuidv4();

    await execute(
      `INSERT INTO Categories (id, name, slug, isActive, createdAt, updatedAt)
       VALUES (@id, @name, @slug, 1, GETDATE(), GETDATE())`,
      { id: laptopCategoryId, name: 'Laptops', slug: 'laptops' }
    );
    await execute(
      `INSERT INTO Categories (id, name, slug, isActive, createdAt, updatedAt)
       VALUES (@id, @name, @slug, 1, GETDATE(), GETDATE())`,
      { id: accessoriesCategoryId, name: 'Accessories', slug: 'accessories' }
    );
    await execute(
      `INSERT INTO Categories (id, name, slug, isActive, createdAt, updatedAt)
       VALUES (@id, @name, @slug, 1, GETDATE(), GETDATE())`,
      { id: componentsCategoryId, name: 'Components', slug: 'components' }
    );
    console.log('Created categories');

    // Sample products
    const sampleLaptops = [
      {
        name: 'Apple MacBook Pro M3',
        slug: 'apple-macbook-pro-m3',
        brand: 'Apple',
        categoryId: laptopCategoryId,
        description: '14-inch Pro display, M3 chip, 16GB RAM, 512GB SSD storage, gold color, 18-hour battery life',
        specifications: JSON.stringify({
          processor: 'Apple M3',
          processorBrand: 'Apple',
          processorModel: 'M3',
          ram: '16GB',
          ramType: 'DDR5',
          storage: '512GB',
          storageType: 'NVMe',
          gpu: 'Integrated GPU',
          displaySize: '14"',
          displayResolution: '3024 x 1946',
          displayType: 'Mini-LED',
          battery: '18 hours',
          ports: 'USB-C, Thunderbolt',
          os: 'macOS',
          weight: '1.6 kg',
          warranty: '1 year',
          color: 'Gold',
        }),
        retailPrice: 1999,
        wholesalePrice: 1799,
        wholesaleMinQty: 5,
        costPrice: 1300,
        stock: 12,
        lowStockThreshold: 3,
        images: JSON.stringify(['macbook-pro-m3.jpg', 'gold-macbook.jpg']),
        condition: 'new',
        isFeatured: 1,
        isNewArrival: 1,
        isBestSeller: 1,
        isActive: 1,
        tags: JSON.stringify(['Macbook', 'Apple', 'Pro', 'M3', '14-inch']),
      },
      {
        name: 'Dell XPS 15',
        slug: 'dell-xps-15',
        brand: 'Dell',
        categoryId: laptopCategoryId,
        description: '15.6-inch 4K touchscreen, Intel i9 processor, 32GB RAM, 1TB SSD, Platinum Silver color',
        specifications: JSON.stringify({
          processor: 'Intel Core i9-13900H',
          processorBrand: 'Intel',
          processorModel: 'i9-13900H',
          ram: '32GB',
          ramType: 'DDR5',
          storage: '1TB',
          storageType: 'NVMe',
          gpu: 'Intel Arc A770M',
          displaySize: '15.6"',
          displayResolution: '3840 x 2400',
          displayType: 'IPS Touch',
          battery: '12 hours',
          ports: 'USB-C, USB-A, HDMI, SD Card',
          os: 'Windows 11',
          weight: '2.0 kg',
          warranty: '1 year',
          color: 'Platinum Silver',
        }),
        retailPrice: 1599,
        wholesalePrice: 1399,
        wholesaleMinQty: 5,
        costPrice: 950,
        stock: 8,
        lowStockThreshold: 2,
        images: JSON.stringify(['dell-xps-15.jpg', 'dell-xps-15-silver.jpg']),
        condition: 'new',
        isFeatured: 1,
        isNewArrival: 0,
        isBestSeller: 1,
        isActive: 1,
        tags: JSON.stringify(['Dell', 'XPS', '15-inch', '4K', 'Touchscreen']),
      },
      {
        name: 'Lenovo ThinkPad X1 Carbon',
        slug: 'lenovo-thinkpad-x1-carbon',
        brand: 'Lenovo',
        categoryId: laptopCategoryId,
        description: 'Business ultraportable with 14" display, Intel i7, 16GB RAM, 512GB SSD',
        specifications: JSON.stringify({
          processor: 'Intel Core i7-1365U',
          processorBrand: 'Intel',
          processorModel: 'i7-1365U',
          ram: '16GB',
          ramType: 'DDR5',
          storage: '512GB',
          storageType: 'NVMe',
          gpu: 'Intel Iris Xe Graphics',
          displaySize: '14"',
          displayResolution: '2880 x 1800',
          displayType: 'OLED',
          battery: '15 hours',
          ports: 'USB-C, USB-A, HDMI',
          os: 'Windows 11 Pro',
          weight: '1.13 kg',
          warranty: '3 years',
          color: 'Black',
        }),
        retailPrice: 1699,
        wholesalePrice: 1499,
        wholesaleMinQty: 5,
        costPrice: 900,
        stock: 15,
        lowStockThreshold: 4,
        images: JSON.stringify(['thinkpad-x1-carbon.jpg', 'thinkpad-keyboard.jpg']),
        condition: 'new',
        isFeatured: 1,
        isNewArrival: 1,
        isBestSeller: 0,
        isActive: 1,
        tags: JSON.stringify(['ThinkPad', 'Business', 'Ultrabook', '14-inch', 'i7']),
      },
      {
        name: 'HP Spectre x360',
        slug: 'hp-spectre-x360',
        brand: 'HP',
        categoryId: laptopCategoryId,
        description: '13.5-inch 2-in-1 convertible with 3K OLED display',
        specifications: JSON.stringify({
          processor: 'Intel Core i7-1360P',
          processorBrand: 'Intel',
          processorModel: 'i7-1360P',
          ram: '16GB',
          ramType: 'DDR5',
          storage: '1TB',
          storageType: 'NVMe',
          gpu: 'Intel Iris Xe Graphics',
          displaySize: '13.5"',
          displayResolution: '3000 x 2000',
          displayType: 'OLED Touch',
          battery: '12 hours',
          ports: 'USB-C, Thunderbolt 4, HDMI',
          os: 'Windows 11',
          weight: '1.36 kg',
          warranty: '1 year',
          color: 'Nightfall Black',
        }),
        retailPrice: 1499,
        wholesalePrice: 1299,
        wholesaleMinQty: 5,
        costPrice: 750,
        stock: 6,
        lowStockThreshold: 2,
        images: JSON.stringify(['spectre-x360.jpg', 'spectre-tablet.jpg']),
        condition: 'new',
        isFeatured: 0,
        isNewArrival: 1,
        isBestSeller: 0,
        isActive: 1,
        tags: JSON.stringify(['HP', 'Spectre', '2-in-1', 'Convertible', 'OLED']),
      },
      {
        name: 'ASUS ROG Zephyrus G14',
        slug: 'asus-rog-zephyrus-g14',
        brand: 'ASUS',
        categoryId: laptopCategoryId,
        description: '14-inch gaming laptop with AMD Ryzen 9, RTX 4060, 32GB RAM, 1TB SSD',
        specifications: JSON.stringify({
          processor: 'AMD Ryzen 9 7940HS',
          processorBrand: 'AMD',
          processorModel: 'Ryzen 9 7940HS',
          ram: '32GB',
          ramType: 'DDR5',
          storage: '1TB',
          storageType: 'NVMe',
          gpu: 'NVIDIA GeForce RTX 4060',
          displaySize: '14"',
          displayResolution: '2560 x 1440',
          displayType: 'IPS QHD',
          battery: '10 hours',
          ports: 'USB-C, USB-A, HDMI 2.1',
          os: 'Windows 11',
          weight: '1.7 kg',
          warranty: '2 years',
          color: 'Eclipse Gray',
        }),
        retailPrice: 1799,
        wholesalePrice: 1599,
        wholesaleMinQty: 5,
        costPrice: 1100,
        stock: 10,
        lowStockThreshold: 3,
        images: JSON.stringify(['zephyrus-g14.jpg', 'rog-logo.jpg']),
        condition: 'new',
        isFeatured: 1,
        isNewArrival: 0,
        isBestSeller: 1,
        isActive: 1,
        tags: JSON.stringify(['ASUS', 'ROG', 'Gaming', 'RTX 4060', '14-inch']),
      },
      {
        name: 'Apple MacBook Air M2',
        slug: 'apple-macbook-air-m2',
        brand: 'Apple',
        categoryId: laptopCategoryId,
        description: '13.6-inch Liquid Retina display, M2 chip, 8GB RAM, 256GB SSD, fanless design',
        specifications: JSON.stringify({
          processor: 'Apple M2',
          processorBrand: 'Apple',
          processorModel: 'M2',
          ram: '8GB',
          ramType: 'LPDDR5',
          storage: '256GB',
          storageType: 'NVMe',
          gpu: 'Integrated GPU',
          displaySize: '13.6"',
          displayResolution: '2560 x 1664',
          displayType: 'Liquid Retina',
          battery: '18 hours',
          ports: 'USB-C, Thunderbolt',
          os: 'macOS',
          weight: '1.24 kg',
          warranty: '1 year',
          color: 'Starlight',
        }),
        retailPrice: 1199,
        wholesalePrice: 1049,
        wholesaleMinQty: 5,
        costPrice: 650,
        stock: 20,
        lowStockThreshold: 5,
        images: JSON.stringify(['macbook-air-m2.jpg', 'starlight-macbook.jpg']),
        condition: 'new',
        isFeatured: 1,
        isNewArrival: 0,
        isBestSeller: 1,
        isActive: 1,
        tags: JSON.stringify(['Macbook', 'Air', 'M2', '13-inch', 'Fanless']),
      },
      {
        name: 'Microsoft Surface Laptop 5',
        slug: 'microsoft-surface-laptop-5',
        brand: 'Microsoft',
        categoryId: laptopCategoryId,
        description: '13.5-inch touchscreen, Intel i7, 16GB RAM, 512GB SSD',
        specifications: JSON.stringify({
          processor: 'Intel Core i7-1255U',
          processorBrand: 'Intel',
          processorModel: 'i7-1255U',
          ram: '16GB',
          ramType: 'LPDDR5',
          storage: '512GB',
          storageType: 'NVMe',
          gpu: 'Intel Iris Xe Graphics',
          displaySize: '13.5"',
          displayResolution: '2256 x 1504',
          displayType: 'PixelSense Touch',
          battery: '17 hours',
          ports: 'USB-C, USB-A, Surface Connect',
          os: 'Windows 11',
          weight: '1.28 kg',
          warranty: '1 year',
          color: 'Sage',
        }),
        retailPrice: 1299,
        wholesalePrice: 1149,
        wholesaleMinQty: 5,
        costPrice: 700,
        stock: 9,
        lowStockThreshold: 2,
        images: JSON.stringify(['surface-laptop-5.jpg', 'surface-alcantara.jpg']),
        condition: 'new',
        isFeatured: 0,
        isNewArrival: 1,
        isBestSeller: 0,
        isActive: 1,
        tags: JSON.stringify(['Microsoft', 'Surface', 'Touchscreen', '13.5-inch', 'Alcantara']),
      },
      {
        name: 'Acer Swift X',
        slug: 'acer-swift-x',
        brand: 'Acer',
        categoryId: laptopCategoryId,
        description: '14-inch creator laptop with AMD Ryzen 7, RTX 3050',
        specifications: JSON.stringify({
          processor: 'AMD Ryzen 7 6800U',
          processorBrand: 'AMD',
          processorModel: 'Ryzen 7 6800U',
          ram: '16GB',
          ramType: 'DDR5',
          storage: '512GB',
          storageType: 'NVMe',
          gpu: 'NVIDIA GeForce RTX 3050',
          displaySize: '14"',
          displayResolution: '1920 x 1080',
          displayType: 'IPS',
          battery: '11 hours',
          ports: 'USB-C, USB-A, HDMI',
          os: 'Windows 11',
          weight: '1.39 kg',
          warranty: '2 years',
          color: 'Steel Gray',
        }),
        retailPrice: 1099,
        wholesalePrice: 949,
        wholesaleMinQty: 5,
        costPrice: 550,
        stock: 14,
        lowStockThreshold: 3,
        images: JSON.stringify(['swift-x.jpg', 'swift-x-side.jpg']),
        condition: 'new',
        isFeatured: 0,
        isNewArrival: 1,
        isBestSeller: 0,
        isActive: 1,
        tags: JSON.stringify(['Acer', 'Swift', 'Creator', 'RTX 3050', '14-inch']),
      },
      {
        name: 'Samsung Galaxy Book3 Pro',
        slug: 'samsung-galaxy-book3-pro',
        brand: 'Samsung',
        categoryId: laptopCategoryId,
        description: '16-inch AMOLED 2K display, Intel i7, 16GB RAM, 1TB SSD',
        specifications: JSON.stringify({
          processor: 'Intel Core i7-1360P',
          processorBrand: 'Intel',
          processorModel: 'i7-1360P',
          ram: '16GB',
          ramType: 'LPDDR5',
          storage: '1TB',
          storageType: 'NVMe',
          gpu: 'Intel Iris Xe Graphics',
          displaySize: '16"',
          displayResolution: '2880 x 1800',
          displayType: 'AMOLED',
          battery: '16 hours',
          ports: 'USB-C, Thunderbolt 4, HDMI',
          os: 'Windows 11',
          weight: '1.56 kg',
          warranty: '1 year',
          color: 'Graphite',
        }),
        retailPrice: 1899,
        wholesalePrice: 1699,
        wholesaleMinQty: 5,
        costPrice: 1000,
        stock: 5,
        lowStockThreshold: 2,
        images: JSON.stringify(['galaxy-book3-pro.jpg', 's-pen.jpg']),
        condition: 'new',
        isFeatured: 0,
        isNewArrival: 1,
        isBestSeller: 0,
        isActive: 1,
        tags: JSON.stringify(['Samsung', 'Galaxy Book', 'AMOLED', '16-inch', 'S Pen']),
      },
      {
        name: 'Refurbished Dell Latitude 7420',
        slug: 'refurbished-dell-latitude-7420',
        brand: 'Dell',
        categoryId: laptopCategoryId,
        description: 'Business-grade 14" laptop, Intel i5, 8GB RAM, 256GB SSD, professionally refurbished',
        specifications: JSON.stringify({
          processor: 'Intel Core i5-1135G7',
          processorBrand: 'Intel',
          processorModel: 'i5-1135G7',
          ram: '8GB',
          ramType: 'DDR4',
          storage: '256GB',
          storageType: 'SSD',
          gpu: 'Intel Iris Xe Graphics',
          displaySize: '14"',
          displayResolution: '1920 x 1080',
          displayType: 'IPS',
          battery: '10 hours',
          ports: 'USB-C, USB-A, HDMI',
          os: 'Windows 10 Pro',
          weight: '1.27 kg',
          warranty: '90 days',
          color: 'Black',
        }),
        retailPrice: 499,
        wholesalePrice: 449,
        wholesaleMinQty: 10,
        costPrice: 300,
        stock: 25,
        lowStockThreshold: 5,
        images: JSON.stringify(['latitude-7420-refurb.jpg', 'dell-logo.jpg']),
        condition: 'refurbished',
        isFeatured: 0,
        isNewArrival: 0,
        isBestSeller: 0,
        isActive: 1,
        tags: JSON.stringify(['Dell', 'Latitude', 'Business', 'Refurbished', '14-inch']),
      },
      {
        name: 'Used MacBook Pro 13-inch M1',
        slug: 'used-macbook-pro-m1',
        brand: 'Apple',
        categoryId: laptopCategoryId,
        description: '13.3-inch Retina display, Apple M1 chip, 8GB RAM, 256GB SSD, space gray, lightly used',
        specifications: JSON.stringify({
          processor: 'Apple M1',
          processorBrand: 'Apple',
          processorModel: 'M1',
          ram: '8GB',
          ramType: 'LPDDR4X',
          storage: '256GB',
          storageType: 'NVMe',
          gpu: 'Integrated GPU',
          displaySize: '13.3"',
          displayResolution: '2560 x 1600',
          displayType: 'Retina',
          battery: '8 hours remaining',
          ports: 'USB-C, Thunderbolt',
          os: 'macOS Ventura',
          weight: '1.4 kg',
          warranty: '30 days',
          color: 'Space Gray',
        }),
        retailPrice: 699,
        wholesalePrice: 629,
        wholesaleMinQty: 5,
        costPrice: 400,
        stock: 7,
        lowStockThreshold: 2,
        images: JSON.stringify(['macbook-pro-m1-used.jpg', 'used-macbook.jpg']),
        condition: 'used',
        isFeatured: 0,
        isNewArrival: 0,
        isBestSeller: 0,
        isActive: 1,
        tags: JSON.stringify(['Apple', 'MacBook Pro', 'M1', 'Used', '13-inch']),
      },
    ];

    for (const product of sampleLaptops) {
      const id = uuidv4();
      await execute(
        `INSERT INTO Products (id, name, slug, brand, categoryId, description, specifications, retailPrice, wholesalePrice, wholesaleMinQty, costPrice, stock, lowStockThreshold, images, condition, isFeatured, isNewArrival, isBestSeller, isActive, tags, averageRating, numReviews, createdAt, updatedAt)
         VALUES (@id, @name, @slug, @brand, @categoryId, @description, @specifications, @retailPrice, @wholesalePrice, @wholesaleMinQty, @costPrice, @stock, @lowStockThreshold, @images, @condition, @isFeatured, @isNewArrival, @isBestSeller, @isActive, @tags, 0, 0, GETDATE(), GETDATE())`,
        { id, ...product }
      );
    }
    console.log(`Inserted ${sampleLaptops.length} products`);

    // Create sample users
    const hashedPassword = await bcrypt.hash('password123', 12);

    const users = [
      {
        id: uuidv4(),
        name: 'Ahmed Khan',
        email: 'ahmed@example.com',
        password: hashedPassword,
        role: 'customer',
        phone: '+923001234567',
        addresses: JSON.stringify([
          { label: 'Home', street: '123 Main Street', city: 'Lahore', state: 'Punjab', zip: '54000', country: 'Pakistan', isDefault: true },
        ]),
        isBlocked: 0,
      },
      {
        id: uuidv4(),
        name: 'Fatima Ali',
        email: 'fatima@example.com',
        password: hashedPassword,
        role: 'wholesale_customer',
        wholesaleStatus: 'approved',
        businessName: 'Ali Traders',
        phone: '+923219876543',
        addresses: JSON.stringify([
          { label: 'Office', street: '45 Business Avenue', city: 'Karachi', state: 'Sindh', zip: '75000', country: 'Pakistan', isDefault: true },
        ]),
        isBlocked: 0,
      },
      {
        id: uuidv4(),
        name: 'Admin User',
        email: 'admin@laptopstore.pk',
        password: hashedPassword,
        role: 'admin',
        phone: '+923005551234',
        isBlocked: 0,
      },
      {
        id: uuidv4(),
        name: 'Manager User',
        email: 'manager@laptopstore.pk',
        password: hashedPassword,
        role: 'manager',
        phone: '+923005555678',
        isBlocked: 0,
      },
    ];

    for (const user of users) {
      await execute(
        `INSERT INTO Users (id, name, email, password, role, wholesaleStatus, businessName, phone, addresses, isBlocked, createdAt, updatedAt)
         VALUES (@id, @name, @email, @password, @role, ISNULL(@wholesaleStatus, 'none'), @businessName, @phone, @addresses, @isBlocked, GETDATE(), GETDATE())`,
        {
          id: user.id,
          name: user.name,
          email: user.email,
          password: user.password,
          role: user.role,
          wholesaleStatus: user.wholesaleStatus || 'none',
          businessName: user.businessName || null,
          phone: user.phone || null,
          addresses: user.addresses || null,
          isBlocked: user.isBlocked || 0,
        }
      );
    }
    console.log(`Inserted ${users.length} users`);

    console.log('Database seeding completed successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Seeding error:', error);
    process.exit(1);
  }
};

seedData();
